[project]
name = "cluefin-langgraph"
version = "0.1.0"
description = "Cluefin Agent using LangGraph"
readme = "README.md"
authors = [
    { name = "Hangoo Kang", email = "kgcrom@hotmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "langchain>=0.3.27",
    "langgraph==0.6.0",
    "pydantic==2.11.7",
    "cluefin_openapi",
]

[project.optional-dependencies]
openai = [
    "langchain-openai>=0.3.28",
    "tiktoken>=0.9.0",
]

[project.scripts]
cluefin-langgraph = "cluefin_langgraph:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
